---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  transport:
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[singularity::default]
      - recipe[zookeeper::default]
      - recipe[zookeeper::service]
    attributes:
      singularity:
        port: 7099
        zk_hosts:
          - 'localhost:2181'
      mesos:
        mesosphere:
          with_zookeeper: false
        master:
          quorum: 1
        slave:
          attributes:
            rackid: us-east-1b
      zookeeper:
        service_style: upstart

  - name: executor_package
    run_list:
      - recipe[singularity::executor]
    attributes:
      singularity:
        executor:
          s3_bucket: example

  - name: executor_source
    run_list:
      - recipe[singularity::executor]
    attributes:
      singularity:
        install_type: source
        executor:
          s3_bucket: example
